drop database if exists Lms;

create database lms;

use lms;

drop Table if exists LeaveDetails;

Drop Table If Exists Employee;

CREATE TABLE EMPLOYEE(
  EMP_ID INT PRIMARY KEY,
  EMP_NAME VARCHAR(20) NOT NULL,
  EMP_EMAIL VARCHAR(30) NOT NULL,
  EMP_MOB_NO BIGINT NOT NULL,
  EMP_DPT_NAME VARCHAR(20),
  EMP_DATE_JOINED DATE NOT NULL,
  EMP_MGR_ID INT ,
  FOREIGN KEY (EMP_MGR_ID) REFERENCES EMPLOYEE(EMP_ID),
  EMP_LEAVE_BALANCE INT
  );

  -- create table LEAVE_HISTORY
 CREATE TABLE LeaveDetails (
  LEA_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  LEA_START_DATE DATE NOT NULL,
  LEA_END_DATE DATE NOT NULL,
  LEA_NO_OF_DAYS INT,
  LEA_REASON VARCHAR(100),
  LEA_TYPE ENUM ('EL'),
  LEA_APPLIED_ON DATE,
  LEA_MGR_COMMENTS VARCHAR(100),
  EMP_ID INT(11),
  FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
  LEA_STATUS ENUM('APPROVED','DENIED','PENDING')
  );
  
